// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbugwviqysfvjzmbzoga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxidWd3dmlxeXNmdmp6bWJ6b2dhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzAyMTgsImV4cCI6MjA3MDUwNjIxOH0.yHBgQTSMy3GWeSdSvn2EY58B3O66N9pRKmsjVTSAQ1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});