// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vchejjnhwuakcxgssazx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjaGVqam5od3Vha2N4Z3NzYXp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MTU4MjMsImV4cCI6MjA3MzA5MTgyM30.kaNfiZNTsOLS2p-HJPHCZJpZf75WPUmlccEcLFTabug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});